version: "3"
services:

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.4.2
    user: apm-server
    ports:
      - 7200:7200
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./apm-config/apm-server.yml:/usr/share/apm-server/apm-server.yml
    command: /usr/share/apm-server/apm-server -e -c /usr/share/apm-server/apm-server.yml -E apm-server.host=apm-server:7200 --strict.perms=false
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:7200/polls']
      retries: 6
    networks:
      - apm

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:9200/_cat/health']
    networks:
      - apm

  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:5601/']
      retries: 6
    networks:
      - apm

networks:
  apm:

